##Crear la base de datos
CREATE DATABASE GIMNASIO_OLYMPUS_SQL;
USE GIMNASIO_OLYMPUS_SQL;

##Crear la tabla para las personas
CREATE TABLE TAB_PERSONAS
(
	ID int auto_increment PRIMARY KEY,
    CEDULA VARCHAR(100),
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMER_APELLIDO VARCHAR(100),
    SEGUNDO_APELLIDO VARCHAR(100),
    FECHA_NAC date,
    TIPO ENUM('Instructor', 'Recepcionista', 'Cliente'),
    MIEMBRO_DESDE DATE,
    INSTRUCTOR_DESDE DATE,
    SALARIO DECIMAL
);


##Crear tabla usuarios
CREATE TABLE TAB_USUARIOS(
	ID_USUARIO int auto_increment PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASS VARCHAR(100),
    ROL VARCHAR(100),
    ID INT,
    CONSTRAINT id_fk FOREIGN KEY (ID) REFERENCES TAB_PERSONAS(ID)
);

drop table tab_usuarios;

##Crear la tabla para las sesiones por los clientes
CREATE TABLE TAB_SESION_REGULAR
(
    ID_SESION_REGULAR INT PRIMARY KEY AUTO_INCREMENT,
    ID_INSTRUCTOR INT,
    DESCRIPCION VARCHAR(100),
    DIA VARCHAR(20),
    HORA TIME,
    cupo int,
    CONSTRAINT id_instructor_fk FOREIGN KEY (ID_INSTRUCTOR) REFERENCES TAB_PERSONAS(ID)
);

##Crear la tabla para las clases por los clientes
CREATE TABLE TAB_CLASE
(
    ID_CLASE INT PRIMARY KEY AUTO_INCREMENT,
    ID_INSTRUCTOR INT,
    DESCRIPCION VARCHAR(100),
    DIA VARCHAR(20),
    hora TIME,
    cupo int,
    CONSTRAINT id_instructor_fk_clase FOREIGN KEY (ID_INSTRUCTOR) REFERENCES TAB_PERSONAS(ID)
);

##Crear la tabla para los talleres por los clientes
CREATE TABLE TAB_TALLER
(
    ID_TALLER INT PRIMARY KEY AUTO_INCREMENT,
    ID_INSTRUCTOR INT,
    DESCRIPCION VARCHAR(100),
    fecha DATE,
    hora TIME,
    cupo int,
    CONSTRAINT id_instructor_fk_taller FOREIGN KEY (ID_INSTRUCTOR) REFERENCES TAB_PERSONAS(ID)
);

##Crear la tabla para las actividades regulares inscritas por los clientes
CREATE TABLE TAB_INSCRIPCION_SESION_REGULAR (
    ID_INSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_SESION_REGULAR INT,
    FECHA_INSCRIPCION DATE,
    CONSTRAINT id_cliente_fk_inscripcion FOREIGN KEY (ID_CLIENTE) REFERENCES TAB_PERSONAS(ID),
    CONSTRAINT id_sesion_regular_fk_inscripcion FOREIGN KEY (ID_SESION_REGULAR) REFERENCES TAB_SESION_REGULAR(ID_SESION_REGULAR)
);

CREATE TABLE TAB_INSCRIPCION_CLASE (
    ID_INSCRIPCION_CLASE INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_CLASE INT,
    FECHA_INSCRIPCION DATE,
    CONSTRAINT id_cliente_fk_inscripcion_clase FOREIGN KEY (ID_CLIENTE) REFERENCES TAB_PERSONAS(ID),
    CONSTRAINT id_clase_fk_inscripcion_clase FOREIGN KEY (ID_CLASE) REFERENCES TAB_CLASE(ID_CLASE)
);

CREATE TABLE TAB_INSCRIPCION_TALLER (
    ID_INSCRIPCION_TALLER INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_TALLER INT,
    FECHA_INSCRIPCION DATE,
    CONSTRAINT id_cliente_fk_inscripcion_taller FOREIGN KEY (ID_CLIENTE) REFERENCES TAB_PERSONAS(ID),
    CONSTRAINT id_taller_fk_inscripcion_taller FOREIGN KEY (ID_TALLER) REFERENCES TAB_TALLER(ID_TALLER)
);


##Inserts para pruebas 

##Insert personas
INSERT INTO TAB_PERSONAS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NAC, TIPO, MIEMBRO_DESDE, INSTRUCTOR_DESDE, SALARIO)
VALUES ('123456789', 'Juan', 'Pérez', 'González', '1990-05-15', 'Cliente', '2023-01-01', NULL, NULL);

INSERT INTO TAB_PERSONAS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NAC, TIPO, MIEMBRO_DESDE, INSTRUCTOR_DESDE, SALARIO)
VALUES ('987654321', 'María', 'López', 'Rodríguez', '1985-08-20', 'Cliente', '2022-11-10', NULL, NULL);

INSERT INTO TAB_PERSONAS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NAC, TIPO, MIEMBRO_DESDE, INSTRUCTOR_DESDE, SALARIO)
VALUES ('456789123', 'Carlos', 'García', 'Martínez', '1995-03-30', 'Instructor', NULL, '2020-02-15', 1500.00);

INSERT INTO TAB_PERSONAS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NAC, TIPO, MIEMBRO_DESDE, INSTRUCTOR_DESDE, SALARIO)
VALUES ('789123456', 'Ana', 'Ruiz', 'Díaz', '1988-11-07', 'Recepcionista', NULL, NULL, 1200.00);

INSERT INTO TAB_PERSONAS (CEDULA, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NAC, TIPO, MIEMBRO_DESDE, INSTRUCTOR_DESDE, SALARIO)
VALUES ('654321987', 'Pedro', 'Sánchez', 'Fernández', '1992-09-25', 'Cliente', '2023-03-18', NULL, NULL);

##Insert usuarios
INSERT INTO TAB_USUARIOS (USERNAME, PASS, ROL, ID)
VALUES ('juan123', 'contraseña123', 'Cliente', 1);

INSERT INTO TAB_USUARIOS (USERNAME, PASS, ROL, ID)
VALUES ('maria456', 'contraseña456', 'Cliente', 2);

INSERT INTO TAB_USUARIOS (USERNAME, PASS, ROL, ID)
VALUES ('carlos789', 'contraseña789', 'Instructor', 3);

INSERT INTO TAB_USUARIOS (USERNAME, PASS, ROL, ID)
VALUES ('ana987', 'contraseña987', 'Recepcionista', 4);

INSERT INTO TAB_USUARIOS (USERNAME, PASS, ROL, ID)
VALUES ('pedro654', 'contraseña654', 'Cliente', 5);


